---
title: "Homework 1"
output: github_document
author: [Your name here]
---

```{r setup, include = FALSE}
remotes::install_github("rundel/chunktest")
chunktest::init()

library(testthat)
```


### Task 1 - Re-Implementation

Include a brief description of your implementation here

```{r}
fizzbuzz = function(v) {
  UseMethod("fizzbuzz")
}

fizzbuzz.default = function(v) {

}

```

### Task 2 - Re-Validation & Testing

```{testthat good_input}
test_that("Single Integer", {
  expect_output(fizzbuzz(1L), "\\[1\\] 1") #fizzbuzz(1)
})

test_that("Multiple Integers", {
  expect_output(fizzbuzz(1:2), "\\[1\\] 1\n\\[1\\] 2") #fizzbuzz(1)
})
```

```{r}
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)

fizzbuzz(9:15)
fizzbuzz(15:9)

fizzbuzz(1:12)
```

```{testthat bad_input}
test_that("Single Negative Integer", {
  expect_error(fizzbuzz(-1)) #fizzbuzz(1)
})
```

```{r error=TRUE}
fizzbuzz(-1)
fizzbuzz(-3)
fizzbuzz(-5)

fizzbuzz(TRUE)
fizzbuzz(FALSE)

fizzbuzz(Inf)
fizzbuzz(-Inf)
fizzbuzz(NaN)

fizzbuzz("A")
fizzbuzz(1.5)
fizzbuzz(1i)
fizzbuzz(4i)
```